version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: fastapi-prices
    ports:
      - "80:80"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
